const dataMockup = {
  count: 18,
  next: null,
  previous: null,
  results: [
    {
      id: 14,
      desc: 'Mauricio',
      phone: '5120420085',
      comunication_tool: 'respond.io',
      role: [],
      type: 'whatsapp',
      connection_token: '381076',
      datetime_last_assigned: null,
      purpose_id: 3,
      custom_channel_id: null,
      custom_channel_token: null,
      digisac_service_id: null,
      digisac_user_id: null,
    },
    {
      id: 6,
      desc: 'Renato',
      phone: '4892231980',
      comunication_tool: 'DIGISAC',
      role: [],
      type: 'whatsapp',
      connection_token: '0f76c01a-14e3-4820-a2f7-a59a47cccf95',
      datetime_last_assigned: null,
      purpose_id: 3,
      custom_channel_id: null,
      custom_channel_token: null,
      digisac_service_id: null,
      digisac_user_id: null,
    },
    {
      id: 1,
      desc: 'Não usar 55 48 88145858',
      phone: '554888145858',
      comunication_tool: 'Paused',
      role: [],
      type: 'whatsapp',
      connection_token: 'd8e4ed59-4d04-44bc-acb1-30c90bba6297',
      datetime_last_assigned: '2024-05-23T16:40:27Z',
      purpose_id: 1,
      custom_channel_id: null,
      custom_channel_token: null,
      digisac_service_id: null,
      digisac_user_id: null,
    },
    {
      id: 11,
      desc: 'Vitor - Apolar/Lello/Baggio',
      phone: '4184602739',
      comunication_tool: 'DIGISAC',
      role: [],
      type: 'whatsapp',
      connection_token: 'e0140d38-8ebf-42fa-b556-fb59e383aa56',
      datetime_last_assigned: null,
      purpose_id: 3,
      custom_channel_id: null,
      custom_channel_token: null,
      digisac_service_id: null,
      digisac_user_id: null,
    },
    {
      id: 7,
      desc: 'Matheus',
      phone: '4896047896',
      comunication_tool: 'DIGISAC',
      role: [],
      type: 'whatsapp',
      connection_token: '57de69f1-39c1-4d24-9dec-b9bb56c90dd9',
      datetime_last_assigned: null,
      purpose_id: 3,
      custom_channel_id: null,
      custom_channel_token: null,
      digisac_service_id: null,
      digisac_user_id: null,
    },
    {
      id: 8,
      desc: 'Emerson',
      phone: '5196301671',
      comunication_tool: 'DIGISAC',
      role: [],
      type: 'whatsapp',
      connection_token: 'c3fefad8-0d97-40f7-9bba-6fa9f1d04a21',
      datetime_last_assigned: null,
      purpose_id: 3,
      custom_channel_id: null,
      custom_channel_token: null,
      digisac_service_id: null,
      digisac_user_id: null,
    },
    {
      id: 16,
      desc: 'Mauricio',
      phone: '5180372233',
      comunication_tool: 'DIGISAC',
      role: [],
      type: 'whatsapp',
      connection_token: '8171a082-e201-4551-8f3b-d747711eabc7',
      datetime_last_assigned: null,
      purpose_id: 3,
      custom_channel_id: null,
      custom_channel_token: null,
      digisac_service_id: null,
      digisac_user_id: null,
    },
    {
      id: 17,
      desc: 'Renato',
      phone: '4831810114',
      comunication_tool: 'respond.io',
      role: [],
      type: 'whatsapp',
      connection_token: '381101',
      datetime_last_assigned: null,
      purpose_id: 3,
      custom_channel_id: null,
      custom_channel_token: null,
      digisac_service_id: null,
      digisac_user_id: null,
    },
    {
      id: 18,
      desc: 'Vitor - Apolar/Lello/Baggio',
      phone: '4135421733',
      comunication_tool: 'respond.io',
      role: [],
      type: 'whatsapp',
      connection_token: '381061',
      datetime_last_assigned: null,
      purpose_id: 3,
      custom_channel_id: null,
      custom_channel_token: null,
      digisac_service_id: null,
      digisac_user_id: null,
    },
    {
      id: 20,
      desc: 'Emerson',
      phone: '5120420122',
      comunication_tool: 'respond.io',
      role: [],
      type: 'whatsapp',
      connection_token: '381058',
      datetime_last_assigned: null,
      purpose_id: 3,
      custom_channel_id: null,
      custom_channel_token: null,
      digisac_service_id: null,
      digisac_user_id: null,
    },
    {
      id: 23,
      desc: 'Jhonatan',
      phone: '551142105505',
      comunication_tool: 'respond.io',
      role: [],
      type: 'whatsapp',
      connection_token: '389464',
      datetime_last_assigned: null,
      purpose_id: 3,
      custom_channel_id: null,
      custom_channel_token: null,
      digisac_service_id: null,
      digisac_user_id: null,
    },
    {
      id: 15,
      desc: 'budgeteer',
      phone: '554899038405',
      comunication_tool: 'DIGISAC',
      role: [],
      type: 'whatsapp',
      connection_token: 'da2e984e-6b6a-4281-8558-0c998202e227',
      datetime_last_assigned: null,
      purpose_id: 4,
      custom_channel_id: null,
      custom_channel_token: null,
      digisac_service_id: null,
      digisac_user_id: null,
    },
    {
      id: 21,
      desc: 'Bruno de Brito',
      phone: '5120420117',
      comunication_tool: 'DIGISAC',
      role: [],
      type: 'whatsapp',
      connection_token: 'c9ae9d3e-b5a4-4a21-b786-5edf9ac312b4',
      datetime_last_assigned: null,
      purpose_id: 3,
      custom_channel_id: null,
      custom_channel_token: null,
      digisac_service_id: null,
      digisac_user_id: null,
    },
    {
      id: 19,
      desc: 'Matheus',
      phone: '4831810109',
      comunication_tool: 'respond.io',
      role: [],
      type: 'whatsapp',
      connection_token: '388721',
      datetime_last_assigned: null,
      purpose_id: 3,
      custom_channel_id: null,
      custom_channel_token: null,
      digisac_service_id: null,
      digisac_user_id: null,
    },
    {
      id: 13,
      desc: 'Jhonatan',
      phone: '48992101719',
      comunication_tool: 'DIGISAC',
      role: [],
      type: 'whatsapp',
      connection_token: 'a2fbb057-e883-47d2-8bdb-787de313c20d',
      datetime_last_assigned: null,
      purpose_id: 3,
      custom_channel_id: null,
      custom_channel_token: null,
      digisac_service_id: null,
      digisac_user_id: null,
    },
    {
      id: 4,
      desc: 'Clientes 554888145858',
      phone: '5548991085066',
      comunication_tool: 'Paused',
      role: [
        'lessee',
        'cs_refera',
        'cs_manager',
        'cs_approver',
        'cs_finance',
        'payer',
      ],
      type: 'whatsapp',
      connection_token: 'd8e4ed59-4d04-44bc-acb1-30c90bba6297',
      datetime_last_assigned: '2024-05-23T16:55:55Z',
      purpose_id: 2,
      custom_channel_id: null,
      custom_channel_token: null,
      digisac_service_id: null,
      digisac_user_id: null,
    },
    {
      id: 3,
      desc: 'Twilio',
      phone: '554840420352',
      comunication_tool: 'Twillio',
      role: [
        'lessee',
        'cs_refera',
        'cs_manager',
        'cs_approver',
        'cs_finance',
        'payer',
      ],
      type: 'whatsapp',
      connection_token: '775aee88131b527fb3623a63bd4c0aa5',
      datetime_last_assigned: '2025-07-24T13:53:14.012250Z',
      purpose_id: 2,
      custom_channel_id: null,
      custom_channel_token: null,
      digisac_service_id: null,
      digisac_user_id: null,
    },
    {
      id: 99,
      desc: 'Manoel (Teste)',
      phone: '554831810217',
      comunication_tool: 'Respond.io (Custom Channel Digisac)',
      role: [],
      type: 'whatsapp',
      connection_token: null,
      datetime_last_assigned: null,
      purpose_id: null,
      custom_channel_id: '197ebddcc3d4d5b5512e980321177c6',
      custom_channel_token:
        'ec0afa435d5e4a4b5a1b712c885f7bfcf700906e9e4bd2d802cefd84bfe9fea5',
      digisac_service_id: '6e9aab4c-94fd-47e0-99f2-06ae04caaa0c',
      digisac_user_id: 'c3c4de37-afc8-4be0-96a8-4f1f606eeea3',
    },
  ],
};

module.exports = dataMockup;
